# Generated by Django 4.2.5 on 2023-09-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScreenRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_title", models.CharField(max_length=252)),
                (
                    "video_file",
                    models.FileField(blank=True, default="", upload_to="videos/"),
                ),
                ("video_link", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
